{
 "title": "AS_1",
 "time": { "from": "2020-12-28T21:24:42.567Z", "to": "2020-12-29T09:24:42.567Z" },
 "panels": [
  {
   "title": "Búsquedas globales de \"CORONAVIRUS\" por mes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  NOW() AS \"time\",\r\n  mes AS metric,\r\n  busquedas as value\r\nFROM busquedas_mes_coronavirus\r\nORDER BY mes\r\n"
    }
   ]
  },
  {
   "title": "Búsquedas globales de \"COVID\" por mes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  NOW() AS \"time\",\r\n  mes AS metric,\r\n  busquedas as value\r\nFROM busquedas_mes_covid\r\nORDER BY mes\r\n"
    }
   ]
  },
  {
   "title": "Búsquedas globales de \"MASCARILLA\" por mes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  NOW() AS \"time\",\r\n  mes AS metric,\r\n  busquedas as value\r\nFROM busquedas_mes_mascarilla\r\nORDER BY mes\r\n"
    }
   ]
  },
  {
   "title": "Búsquedas globales de \"MASK\" por mes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  NOW() AS \"time\",\r\n  mes AS metric,\r\n  busquedas as value\r\nFROM busquedas_mes_mask\r\nORDER BY mes\r\n"
    }
   ]
  },
  {
   "title": "Búsquedas globales de \"VACUNA\" por mes",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  NOW() AS \"time\",\r\n  mes AS metric,\r\n  busquedas as value\r\nFROM busquedas_mes_vacuna\r\nORDER BY mes\r\n"
    }
   ]
  },
  {
   "title": "Búsquedas globales de \"VACCINE\" por mes",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  NOW() AS \"time\",\r\n  mes AS metric,\r\n  busquedas as value\r\nFROM busquedas_mes_vaccine\r\nORDER BY mes\r\n"
    }
   ]
  }
 ]
}