{
 "title": "AS_2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Palabras más buscadas en España durante 2020",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM top_busquedas_espana_2020\nORDER BY top \n"
    }
   ]
  },
  {
   "title": "Palabras más buscadas en EEUU durante 2020",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM top_busquedas_eeuu_2020\nORDER BY top \n"
    }
   ]
  },
  {
   "title": "Palabras más buscadas en Italia durante 2020",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM top_busquedas_italia_2020\nORDER BY top \n"
    }
   ]
  }
 ]
}