{
 "title": "AS_3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "\"CORONAVIRUS\" vs \"COVID\" en EEUU",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  fecha AS metric,\r\n  coronavirus as value,\r\n  covid as value\r\nFROM coronavirus_vs_covid_eeuu\r\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Media de \"CORONAVIRUS\" VS \"COVID\" en EEUU",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  fecha AS metric,\r\n  coronavirus as value,\r\n  covid as value\r\nFROM coronavirus_vs_covid_eeuu\r\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "\"CORONAVIRUS\" vs \"COVID\" en ESPAÑA",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  fecha AS metric,\r\n  coronavirus as value,\r\n  covid as value\r\nFROM coronavirus_vs_covid_espana\r\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Media de \"CORONAVIRUS\" VS \"COVID\" en ESPAÑA",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS metric,\n  coronavirus as value,\n  covid as value\nFROM coronavirus_vs_covid_espana\nORDER BY fecha\n"
    }
   ]
  }
 ]
}