{
 "title": "AS_4",
 "time": { "from": "2021-01-10T05:56:10.234Z", "to": "2021-01-10T17:56:10.234Z" },
 "panels": [
  {
   "title": "Búsqueda de \"SÍNTOMAS\" en España por semana",
   "type": "bargauge",
   "gridPos": { "h": 31, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  fecha AS metric,\n  sintomas as value\nFROM busqueda_sintomas_espana\nORDER BY fecha\n"
    }
   ]
  },
  {
   "title": "Búsqueda de \"ERTE\" en España por semana",
   "type": "bargauge",
   "gridPos": { "h": 31, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  fecha AS metric,\n  erte as value\nFROM busqueda_erte_espana\nORDER BY fecha\n"
    }
   ]
  },
  {
   "title": "Búsqueda de \"CONFINAMIENTO\" en España por semana",
   "type": "bargauge",
   "gridPos": { "h": 32, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  fecha AS metric,\n  confinamiento as value\nFROM busqueda_confinamiento_espana\nORDER BY fecha\n"
    }
   ]
  },
  {
   "title": "Búsqueda de \"TOQUE DE QUEDA\" en España por semana",
   "type": "bargauge",
   "gridPos": { "h": 32, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  NOW() AS \"time\",\r\n  fecha AS metric,\r\n  toquequeda as value\r\nFROM busqueda_toque_queda_espana\r\nORDER BY fecha"
    }
   ]
  }
 ]
}