version: "3.9"
services:
    crate:
        image: 'crate'
        network_mode: host
        ports:
            - "4200:4200"
    grafana:
        image: 'grafana/grafana'
        network_mode: host
        ports:
             - "3000:3000"
    aplicacion:
        image: 'jmiguel013/grafana_crate:v2'
        network_mode: host
        depends_on:
            - crate
